version: '2'
services:
  keybox:
    container_name: keybox
    image: anmolnagpal/java
    mem_limit: 1g
    memswap_limit: 1g
    cpu_shares: 20
    ports:
      - "8443:8443"
    volumes:
      - ~/Workspace/keybox:/data:rw
    entrypoint: /data/startKeyBox.sh
    environment:
      dbPassword: 123456
